### ISSUE TITLE
Chapter 1 Model User.js

### ISSUE THREAD

**Issue by Tvalone** [spbooks/NODEJS1#11]
I was going into chapter three changing from the mongolabs to the interal mongo db and got this error, scratching my head wondering what I am doing wrong.
var UserSchema = new db.Schema({  
                 ^  
TypeError: undefined is not a function  
    at Object.<anonymous> (/srv/www/www.cross-town-traffic-software.com/public_html/free-cite/models/User.js:3:18)  
    at Module._compile (module.js:456:26)  
    at Object.Module._extensions..js (module.js:474:10)  
    at Module.load (module.js:356:32)  
    at Function.Module._load (module.js:312:12)  
    at Function.Module.runMain (module.js:497:10)  
    at startup (node.js:119:16)  
    at node.js:906:3

**Comment by Tvalone** [comment]
Ok Toren lets keep this for real issues not your homework.
